leftnav:
- identifier: 2bd32e1f-87e6-d821-c3b4-c67fe3f23365
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 9da2b743-0f04-5eaf-1d9a-a3b55837294d
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 088cfdfd-d259-1b19-f8b2-6b29b42d1870
  name: Instructor Insights
  pageRef: /pages/instructor-insights/
  weight: 30
- identifier: b251c87d-a710-0e6f-638a-bcfb30f5df88
  name: Applying a Constructivist Approach
  pageRef: /pages/instructor-insights/applying-a-constructivist-approach
  parent: 088cfdfd-d259-1b19-f8b2-6b29b42d1870
  weight: 40
- identifier: 2bddb4c1-767a-fcd3-7dc5-eb0585c90151
  name: Building Discussion Through Online and In-Class Activities
  pageRef: /pages/instructor-insights/building-discussion-through-online-and-in-class-activities
  parent: 088cfdfd-d259-1b19-f8b2-6b29b42d1870
  weight: 50
- identifier: 64cfd91b-9723-255c-97e4-da92a1e51d6c
  name: Guiding Students to See the Big Picture
  pageRef: /pages/instructor-insights/guiding-students-to-see-the-big-picture
  parent: 088cfdfd-d259-1b19-f8b2-6b29b42d1870
  weight: 60
- identifier: 7a2eb894-7bfb-fbce-910f-c89930de8046
  name: Engaging Students in Their Writing
  pageRef: /pages/instructor-insights/engaging-students-in-their-writing
  parent: 088cfdfd-d259-1b19-f8b2-6b29b42d1870
  weight: 70
- identifier: 3705cb31-5077-f751-1389-fe2dda777fb5
  name: Teaching Students with Strong Science and Math Backgrounds
  pageRef: /pages/instructor-insights/teaching-students-with-strong-science-and-math-backgrounds
  parent: 088cfdfd-d259-1b19-f8b2-6b29b42d1870
  weight: 80
- identifier: 44d2bec9-c5bc-3937-7585-f099d5bd71c7
  name: Introduction
  pageRef: /pages/introduction
  weight: 90
- identifier: b5b223ff-b3c9-b571-177f-64855b572448
  name: Schools & Classrooms
  pageRef: /pages/schools-classrooms/
  weight: 100
- identifier: ccea0fc0-7b5c-742f-031d-67dca9c56d57
  name: 'Week #2'
  pageRef: /pages/schools-classrooms/week-2
  parent: b5b223ff-b3c9-b571-177f-64855b572448
  weight: 110
- identifier: 67ae5a3e-6ce8-20e4-f998-f7f1244de734
  name: 'Week #3'
  pageRef: /pages/schools-classrooms/week-3
  parent: b5b223ff-b3c9-b571-177f-64855b572448
  weight: 120
- identifier: c64ec322-8836-44e1-a6ec-caa9263f7ec8
  name: Math & Science Education
  pageRef: /pages/math-science-education/
  weight: 130
- identifier: 02b5388b-d455-4e19-a7a8-e9d4981db032
  name: 'Week #4'
  pageRef: /pages/math-science-education/week-4
  parent: c64ec322-8836-44e1-a6ec-caa9263f7ec8
  weight: 140
- identifier: 7ac2bee0-588e-8cbe-42de-bd0480708bed
  name: 'Week #5'
  pageRef: /pages/math-science-education/week-5
  parent: c64ec322-8836-44e1-a6ec-caa9263f7ec8
  weight: 150
- identifier: 1e205692-757d-064e-0a92-6b80e1db144f
  name: 'Week #6'
  pageRef: /pages/math-science-education/week-6
  parent: c64ec322-8836-44e1-a6ec-caa9263f7ec8
  weight: 160
- identifier: 39e19bf4-9261-7fe4-f3fb-29e9f0918a86
  name: 'Week #7'
  pageRef: /pages/math-science-education/week-7
  parent: c64ec322-8836-44e1-a6ec-caa9263f7ec8
  weight: 170
- identifier: b60b81d7-64ba-daf0-79a1-b82c94e8dd25
  name: Technology in the Classroom
  pageRef: /pages/technology-in-the-classroom/
  weight: 180
- identifier: dc30c26c-645c-e811-84ea-4300abda3428
  name: 'Week #8'
  pageRef: /pages/technology-in-the-classroom/week-8
  parent: b60b81d7-64ba-daf0-79a1-b82c94e8dd25
  weight: 190
- identifier: 4ab19fbb-1e96-5165-b342-075c5de540c6
  name: 'Week #9'
  pageRef: /pages/technology-in-the-classroom/week-9
  parent: b60b81d7-64ba-daf0-79a1-b82c94e8dd25
  weight: 200
- identifier: dc5fb216-cacf-4243-5757-a3a93e4bf07a
  name: 'Week #10'
  pageRef: /pages/technology-in-the-classroom/week-10
  parent: b60b81d7-64ba-daf0-79a1-b82c94e8dd25
  weight: 210
- identifier: fe849a17-d4db-501a-ffdc-dc517b8137c0
  name: Modes of Teaching
  pageRef: /pages/modes-of-teaching
  weight: 220
- identifier: 2fe122a1-daea-8d52-f0b9-dc652fedc2f9
  name: Assignments
  pageRef: /pages/assignments/
  weight: 230
- identifier: 8c85940c-397a-0cb4-899d-29dd46d0e82c
  name: Ongoing Assignments
  pageRef: /pages/assignments/ongoing-assignments
  parent: 2fe122a1-daea-8d52-f0b9-dc652fedc2f9
  weight: 240
- identifier: ef6ab5ef-b820-01e3-e5d5-d32bac4f0fd1
  name: Major Assignments
  pageRef: /pages/assignments/major-assignments
  parent: 2fe122a1-daea-8d52-f0b9-dc652fedc2f9
  weight: 250
- identifier: f4c97405-3c54-958b-6e03-826138910e49
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 260
